<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>

            <!-- Edited -->
            <?php 
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                $qty = $StockState->getStockQty($block->escapeHtml($_product->getId()), $block->escapeHtml($_product->getStore()->getWebsiteId()));
                echo '<p style="color:green;">Cantidad: '.$qty.'</p>';
            ?>
            <?php if ($qty < 51) : ?>
                <p style="color: red; font-weight: bold;">Pocos productos en stock</p>
            <?php endif; ?>

            <?php
                $location = $_product->getData('location');
                echo 'Ubicación: '.$location;

                $location_exoploded = explode(" ", $location);
                $user_location = @unserialize (file_get_contents('http://ip-api.com/php/'));
            ?>

            <?php if ($user_location && $user_location['status'] == 'success') :?>
                <?php if ($user_location['city'] != $location_exoploded[0]) :?>
                    <p style="color: white; font-weight: bold; background-color:red;padding:10px">Este producto no se encuentra en su ciudad</p>
                <?php endif; ?>
            <?php endif; ?>
            

            <!-- End Edited -->

        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
